python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_01_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_01/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_01/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_02_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_02/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_02/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_03_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_03/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_03/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_05_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_05/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_05/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_06_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_06/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_06/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_07_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_07/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_07/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_08_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_08/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_08/18k_best_results_085t/
python3.6 dump_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections_21_04_15_18k_best_085t_t11e.csv /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/
python3.6 viz_detections.py /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/Pothhole/rear-load-dataset-front-facing/2021_04_15/ /home/mcwi9/Model_Optimization/ml_nas//Rubicon/SOW2/trainings/cl-12/yolo_backup/detections/ /home/mcwi9/Model_Optimization/ml_nas/Rubicon/SOW2/pothole-retag-data/model_results/Rub-T11e/one-day-data/21_04_15/18k_best_results_085t/